### ISSUE TITLE
Only works with 640x480 output resolution.

### ISSUE THREAD

**Issue by cyrusbehr** [prabhakar-sivanesan/OpenCV-rtsp-server#1]
I was able to run the script using the default arguments and connect to and view the RTSP stream, and it was working correctly. 
However, as soon as I change the output resolution of the RTSP stream by modifying the `--image_width` and `--image_height` arguments in the bash script, then when I connect to the generated RTSP stream, it either only displays a green image, or freezes immediately while displaying strange artifacts: 

![image](https://user-images.githubusercontent.com/17056751/117042660-1d967f80-acc1-11eb-95c6-2cf0787615d7.png)

**Comment by prabhakar-sivanesan** [comment]
The arguments --image_width and --image_height values should match the image shape that you're writing to the rtsp sink. For example: If your image shape grabbed from the camera is (1920,1080,3) then your --image_width should be 1920 and --image_height should be 1080. So, if you're changing the input image shape, then resize your image accordingly before writing into your rtsp sink.

**Comment by cyrusbehr** [comment]
Ok that makes sense. I was mainly confused b/c I thought my webcam was higher resolution but after printing the size of the frame obtained by the call to `ret, frame = self.cap.read()` I confirmed that it is indeed `640x480` so that makes sense.

Thanks for the fast response!
