### ISSUE TITLE
Viewing Video file instead of webcam

### ISSUE THREAD

**Issue by lchunleo** [prabhakar-sivanesan/OpenCV-rtsp-server#3]
Thanks for the great work.

i am trying out your work and noticed that if i changed the videocapture instead of device 0 but to a video file, the output is green screen. Can advise? thank you

**Comment by prabhakar-sivanesan** [comment]
Please check and change the --image_width and --image_height that matches your video stream width and height. By default, width and height are set as 640 and 480 respectively in stream.bash file. You can change that according to your video feed.
For reference can you post the command line that you have used.
