### ISSUE TITLE
Program doesn't run properly

### ISSUE THREAD

**Issue by nyanmn** [prabhakar-sivanesan/OpenCV-rtsp-server#4]
I tried to use the library.
I am trying to stream from a CCTV using RTSP stream.
Once the command starts run

python stream.py --device_id "rtsp//xxxxx" --fps 30 --image_width 640 --image_height 480 --port 8554 --stream_uri /video_stream

SensorFactory's init method run.
But on_need_data(), do_create_element(), do_configure() methods didn't run.

What could be issue?

**Comment by prabhakar-sivanesan** [comment]
Apologies for the delay.
Firstly, this application is used to convert non-IP camera feed to RTSP stream, such that it can be consumed by other devices on the "same network".

By looking at your --device_id param, itseems you already have an rtsp streaming link. Typically you're device_id param should either be an integer value or a video file location.

If my understanding is not correct or if you need somemore clarifications, comment below.

**Comment by prabhakar-sivanesan** [comment]
Closing this issue as we don't have any further comments.
