### ISSUE TITLE
Cannot open camera from open_rstp.py

### ISSUE THREAD

**Issue by vyasn30** [prabhakar-sivanesan/OpenCV-rtsp-server#6]
I am having troubles when I try running open_rtsp.py. I have stream.py running in one terminal with the following command `python3 stream.py --device_id 0 --fps 30 --image_width 640 --image_height 480 --port 8554 --stream_uri /video_stream`. 

In the terminal of where I am running open_rtsp.py, I am getting error `OpenCV(4.5.5) /io/opencv/modules/videoio/src/cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): rtsp://192.168.1.7:8554/video_stream in function 'icvExtractPattern'`

**Comment by prabhakar-sivanesan** [comment]
I couldn't exactly replicate this issue but I found a potential bug which could cause this. I have updated the repo now, pull the latest commit and check. 
Let know if the issue still persist.

**Comment by prabhakar-sivanesan** [comment]
Closing this issue as we don't have any further comments
